name: base
channels:
- conda-forge
dependencies:
- python=3.11.5
- pip<=23.2.1
- pip:
  - mlflow==2.7.1
  - cloudpickle==2.2.1
  - numpy==1.24.3
  - packaging==23.2
  - pyyaml==6.0
  - scikit-learn==1.3.0
